
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sanzz
 */
public class TugasWarna3 extends javax.swing.JFrame {
    int jbNo=1;
    
    Color[] colors = {Color.RED, Color.BLUE, Color.GREEN}; // Warna yang akan digunakan
    /**
     * Creates new form TugasWarna3
     */
    public TugasWarna3() {
        initComponents();
        updateButtonColors();
        setTitle("Sandy Meliyawan - 2169700003");
    }
    
    private void updateButtonColors() {
        jbLight1.setBackground(jbNo == 1 ? colors[0] : Color.BLACK);
        jbLight2.setBackground(jbNo == 2 ? colors[0] : Color.BLACK);
        jbLight3.setBackground(jbNo == 3 ? colors[0] : Color.BLACK);
        jbLight4.setBackground(jbNo == 4 ? colors[0] : Color.BLACK);
        jbLight5.setBackground(jbNo == 5 ? colors[0] : Color.BLACK);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbMerah = new javax.swing.JRadioButton();
        rbBiru = new javax.swing.JRadioButton();
        rbHijau = new javax.swing.JRadioButton();
        jbLight1 = new javax.swing.JButton();
        jbLight2 = new javax.swing.JButton();
        jbLight3 = new javax.swing.JButton();
        jbLight4 = new javax.swing.JButton();
        jbLight5 = new javax.swing.JButton();
        jbLeft = new javax.swing.JButton();
        jbRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbMerah);
        rbMerah.setText("MERAH");
        rbMerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMerahActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbBiru);
        rbBiru.setText("BIRU");
        rbBiru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBiruActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbHijau);
        rbHijau.setText("HIJAU");
        rbHijau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHijauActionPerformed(evt);
            }
        });

        jbLeft.setText("<");
        jbLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLeftActionPerformed(evt);
            }
        });

        jbRight.setText(">");
        jbRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbLight1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLight2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(rbMerah)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLight3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(rbBiru)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbLight4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLight5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbHijau)
                        .addGap(62, 62, 62))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRight, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMerah)
                    .addComponent(rbBiru)
                    .addComponent(rbHijau))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbLight1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbLight2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbLight3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLight4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLight5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRight)
                    .addComponent(jbLeft))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMerahActionPerformed
        // TODO add your handling code here:
        if(rbMerah.isSelected()){
            colors[0] = Color.RED;
            jbLight1.setBackground(Color.red);
        }
        updateButtonColors();
    }//GEN-LAST:event_rbMerahActionPerformed

    private void rbBiruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBiruActionPerformed
        // TODO add your handling code here:
        if(rbBiru.isSelected()){
            colors[0] = Color.BLUE;
            jbLight1.setBackground(Color.blue);
        }
        updateButtonColors();
    }//GEN-LAST:event_rbBiruActionPerformed

    private void rbHijauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHijauActionPerformed
        // TODO add your handling code here:
        if(rbHijau.isSelected()){
            colors[0] = Color.GREEN;
            jbLight1.setBackground(Color.green);
        }
        updateButtonColors();
    }//GEN-LAST:event_rbHijauActionPerformed

    private void jbLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLeftActionPerformed
        // TODO add your handling code here:
        jbNo--;
        if (jbNo < 1) {
            jbNo = 5;
        }
        updateButtonColors();
    }//GEN-LAST:event_jbLeftActionPerformed

    private void jbRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRightActionPerformed
        // TODO add your handling code here:
        jbNo++;
        if (jbNo > 5) {
            jbNo = 1;
        }
        updateButtonColors();
    }//GEN-LAST:event_jbRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasWarna3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasWarna3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasWarna3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasWarna3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasWarna3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jbLeft;
    private javax.swing.JButton jbLight1;
    private javax.swing.JButton jbLight2;
    private javax.swing.JButton jbLight3;
    private javax.swing.JButton jbLight4;
    private javax.swing.JButton jbLight5;
    private javax.swing.JButton jbRight;
    private javax.swing.JRadioButton rbBiru;
    private javax.swing.JRadioButton rbHijau;
    private javax.swing.JRadioButton rbMerah;
    // End of variables declaration//GEN-END:variables
    
    

}
